services:
  dingus:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "${FASTAPI_PORT:-8000}:8000"
      - "${STREAMLIT_PORT:-8501}:8501"
    container_name: dingus
    volumes:
      - ./src:/src
      - ./.kube:/.kube
      - ./scripts:/scripts
      - ./data:/data
      - ./logs:/logs
      - ./reports:/reports
    environment:
      - FASTAPI_PORT=8000
  
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-db
    restart: always
    ports:
      - "${QDRANT_PORT:-6333}:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
