{{- if and .Values.ingress ( .Values.ingress.enabled ) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dingus.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "dingus.fullname" . }}
                port:
                  number: 8501
{{- end }}
