name: Code Checks

on:
  pull_request:
    branches:
      - main

env:
  TARGET: build-agent

jobs:
  code-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Create .env and dir
        run: |
          cp sample.env .env
          mkdir -p .kube logs data
          chmod -R 777 .kube logs data

      - name: Start Docker Compose Services
        run: |
          docker compose up --build -d
          docker ps

      - name: Run Code Checks
        run: |
          docker compose exec -T dingus bash /scripts/code-checks.sh

      - name: Stop Docker Compose
        if: always()
        run: docker compose down
